export const IconURL = {
  user_l: require("../assets/icons/user_l.png"),
  user_d: require("../assets/icons/user_d.png"),
  password_l: require("../assets/icons/password_l.png"),
  password_d: require("../assets/icons/password_d.png"),
  hide_l: require("../assets/icons/hide_l.png"),
  hide_d: require("../assets/icons/hide_d.png"),
  show_l: require("../assets/icons/show_l.png"),
  show_d: require("../assets/icons/show_d.png"),
  addmem_l: require("../assets/icons/addmem_l.png"),
  addmem_d: require("../assets/icons/addmem_d.png"),
  aim_l: require("../assets/icons/aim_l.png"),
  aim_d: require("../assets/icons/aim_d.png"),
  alldocument_l: require("../assets/icons/alldocument_l.png"),
  alldocument_d: require("../assets/icons/alldocument_d.png"),
  add_friend:require("../assets/icons/add_friend.png"),
  add_friend_btn:require("../assets/icons/add_friend_btn.png"),
  allphoto_l: require("../assets/icons/allphoto_l.png"),
  allphoto_d: require("../assets/icons/allphoto_d.png"),
  allvideo_l: require("../assets/icons/allvideo_l.png"),
  allvideo_d: require("../assets/icons/allvideo_d.png"),
  attach_l: require("../assets/icons/attach_l.png"),
  attach_d: require("../assets/icons/attach_d.png"),
  addmem:require("../assets/icons/addmem.png"),
  added:require("../assets/icons/added.png"),
  bell_l: require("../assets/icons/bell_l.png"),
  bell_d: require("../assets/icons/bell_d.png"),
  bff_list_l: require("../assets/icons/bff_list_l.png"),
  bff_list_d: require("../assets/icons/bff_list_d.png"),
  bff_request: require("../assets/icons/bff_request.png"),
  birthday: require("../assets/icons/birthday.png"),
  block_l: require("../assets/icons/block_l.png"),
  block_d: require("../assets/icons/block_d.png"),
  block_list_l: require("../assets/icons/block_list_l.png"),
  block_list_d: require("../assets/icons/block_list_d.png"),
  call: require("../assets/icons/call.png"),
  carrot:require("../assets/icons/carrot.png"),
  change_cam: require("../assets/icons/change_cam.png"),
  change_image: require("../assets/icons/change_image.png"),
  chat_func_more_l: require("../assets/icons/chat_func_more_l.png"),
  chat_func_more_d: require("../assets/icons/chat_func_more_d.png"),
  circle:require("../assets/icons/circle.png"),
  close: require("../assets/icons/close.png"),
  close_single:require("../assets/icons/close_single.png"),
  comment: require("../assets/icons/comment.png"),
  editable: require("../assets/icons/editable.png"),
  invite: require("../assets/icons/invite.png"),
  f_request: require("../assets/icons/f_request.png"),
  firstname_l: require("../assets/icons/firstname_l.png"),
  firstname_d: require("../assets/icons/firstname_d.png"),
  flag_l: require("../assets/icons/flag_l.png"),
  flag_d: require("../assets/icons/flag_d.png"),
  friends_l: require("../assets/icons/friends_l.png"),
  friends_d: require("../assets/icons/friends_d.png"),
  groups_l: require("../assets/icons/groups_l.png"),
  groups_d: require("../assets/icons/groups_d.png"),
  icon: require("../assets/icons/icon.png"),
  image_l: require("../assets/icons/image_l.png"),
  image_d: require("../assets/icons/image_d.png"),
  information: require("../assets/icons/information.png"),
  io_l: require("../assets/icons/io_l.png"),
  io_d: require("../assets/icons/io_d.png"),
  is_friend: require("../assets/icons/is_friend.png"),
  is_friend_btn:require("../assets/icons/is_friend_btn.png"),
  is_bff:require("../assets/icons/is_bff.png"),
  is_bff_btn:require("../assets/icons/is_bff_btn.png"),
  pending_btn:require("../assets/icons/pending_btn.png"),
  pending_bff:require("../assets/icons/pending_bff.png"),
  pending_friend:require("../assets/icons/pending_friend.png"),
  leave_l: require("../assets/icons/leave_l.png"),
  leave_d: require("../assets/icons/leave_d.png"), 
  lettuce_l:require("../assets/icons/lettuce_l.png"),
  lettuce_d:require("../assets/icons/lettuce_d.png"),
  livemap_l: require("../assets/icons/livemap_l.png"),
  livemap_d: require("../assets/icons/livemap_d.png"),
  location_l: require("../assets/icons/location_l.png"),
  location_d: require("../assets/icons/location_d.png"),
  love:require("../assets/icons/love.png"),
  loved:require("../assets/icons/loved.png"),
  mail_l: require("../assets/icons/mail_l.png"),
  mail_d: require("../assets/icons/mail_d.png"),
  map_pin: require("../assets/icons/map_pin.png"),
  message_l: require("../assets/icons/message_l.png"),
  message_d: require("../assets/icons/message_d.png"),
  mic_l: require("../assets/icons/mic_l.png"),
  mic_d: require("../assets/icons/mic_d.png"),
  moon: require("../assets/icons/moon.png"),
  more_func: require("../assets/icons/more_func.png"),
  multimedia_l: require("../assets/icons/multimedia_l.png"),
  multimedia_d: require("../assets/icons/multimedia_d.png"),
  my_document: require("../assets/icons/my_document.png"),
  my_gallery: require("../assets/icons/my_gallery.png"),
  nickname_l:require("../assets/icons/nickname_l.png"),
  nickname_d:require("../assets/icons/nickname_d.png"),
  not_found:require("../assets/icons/notfound_404.png"),
  notification:require("../assets/icons/notification.png"),
  onthemic: require("../assets/icons/onthemic.png"),
  open_statuswriter: require("../assets/icons/open_statuswriter.png"),
  opencam_l: require("../assets/icons/opencam_l.png"),
  opencam_d: require("../assets/icons/opencam_d.png"),
  pause:require("../assets/icons/pause.png"),
  phonenumber_l: require("../assets/icons/phonenumber_l.png"),
  phonenumber_d: require("../assets/icons/phonenumber_d.png"),
  pin_l: require("../assets/icons/pin_l.png"),
  pin_d: require("../assets/icons/pin_d.png"),
  play:require("../assets/icons/play.png"),
  plus:require("../assets/icons/plus.png"),
  previous: require("../assets/icons/previous.png"),
  relationship: require("../assets/icons/relationship.png"),
  search: require("../assets/icons/search.png"),
  search_l:require("../assets/icons/search_l.png"),
  search_d:require("../assets/icons/search_d.png"),
  security_l: require("../assets/icons/security_l.png"),
  security_d: require("../assets/icons/security_d.png"),
  send: require("../assets/icons/send.png"),
  sent_request:require("../assets/icons/sent_request.png"),
  setting_l: require("../assets/icons/setting_l.png"),
  setting_d: require("../assets/icons/setting_d.png"),
  share: require("../assets/icons/share.png"),
  showall: require("../assets/icons/showall.png"),
  show_more_func: require("../assets/icons/show_more_func.png"),
  sidebar: require("../assets/icons/sidebar.png"),
  sun: require("../assets/icons/sun.png"),
  tick:require("../assets/icons/tick.png"),
  think: require("../assets/icons/think.png"),
  upgrade_plan: require("../assets/icons/upgrade_plan.png"),
  video_call: require("../assets/icons/video_call.png"),
  visit_card_l: require("../assets/icons/visit_card_l.png"),
  visit_card_d: require("../assets/icons/visit_card_d.png"),
  voice:require("../assets/icons/voice.png"),
  showlist: require("../assets/icons/showlist.png"),
  docx:require("../assets/icons/docx.png"),
  xls:require("../assets/icons/xls.png"),
  ppt:require("../assets/icons/ppt.png"),
  pdf:require("../assets/icons/pdf.png"),
  play_orange:require("../assets/icons/play_orange.png"),
  pause_orange:require("../assets/icons/pause_orange.png"),
  chat_non_select:require("../assets/icons/chat_non-select.png"),
  chat_select:require("../assets/icons/chat_select.png"),
  friends_non_select:require("../assets/icons/friends_non-select.png"),
  friends_select:require("../assets/icons/friends_select.png"),
  map_non_select:require("../assets/icons/map_non-select.png"),
  map_select:require("../assets/icons/map_select.png"),
  setting_non_select:require("../assets/icons/setting_non-select.png"),
  setting_select:require("../assets/icons/setting_select.png"),
  non_select:require("../assets/icons/non-select.png"),
  selected:require("../assets/icons/selected.png"),
  marker:require("../assets/icons/marker.png")
};
